-- This script includes the necessary GRANTS to the &1 User
-- Statements automatically created via save_user_privs.sql script
-- SQL Script located at 
-- SQL Script Source:  

--'CREATEUSER'||USERNAME||'IDENTIFIEDBYXXX'||'DEFAULTTABLESPACE'||DEFAULT_TABLESPACE||'TEMPORARYTABLESPACE'||TEMPORARY_TABLESPACE||';'
---------------------------------------------------------------------------------------------------------------------------------------
--create user &1 identified by xxx default tablespace USERS temporary tablespace TEMP;

--'GRANT'||GRANTED_ROLE||'TO'||GRANTEE||DECODE(ADMIN_OPTION,'YES','WITHADMINOPTION','')||';'
---------------------------------------------------------------------------------------------

--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--
---Look to a previous released one to keep the format

  GRANT ALTER ANY TABLE TO &1; 

  GRANT SELECT ON INSIS_CUST.p_property TO &1  ;
  GRANT INSERT ON INSIS_CUST.p_property TO &1  ;
  GRANT UPDATE ON INSIS_CUST.p_property TO &1;

  GRANT SELECT ON INSIS_CUST.p_property_ADDRESS TO &1  ;
  GRANT INSERT ON INSIS_CUST.p_property_ADDRESS TO &1  ;
  GRANT UPDATE ON INSIS_CUST.p_property_ADDRESS TO &1;

  GRANT SELECT ON INSIS_GEN_CFG_V10.CPRS_OBJECT_SUBT TO &1;
  GRANT SELECT ON INSIS_GEN_CFG_V10.SYSCFG_TRANSLATIONS TO &1;
  GRANT UPDATE ON INSIS_GEN_V10.policy_endorsements TO &1;
  GRANT UPDATE ON INSIS_sys_V10.doc_documents TO &1;
  GRANT EXECUTE ON INSIS_CUST.CUST_POL_BO TO &1;
 -- GRANT SELECT ON INSIS_CUST.LF_EVT_DATA_INEP01C TO &1;
  GRANT SELECT ON SYS.DBA_SCHEDULER_JOBS TO &1;
  GRANT EXECUTE ON SYS.DBMS_ALERT TO &1;
  GRANT SELECT ON SYS.DBMS_ALERT_INFO TO &1;
   
  GRANT SELECT ON  INSIS_GEN_V10.POLICY_COMMISSIONS TO &1;
  GRANT INSERT ON  INSIS_GEN_V10.POLICY_COMMISSIONS TO &1;
  GRANT execute  ON INSIS_GEN_V10.P_COMMISSION_TYPE TO &1 ; 

 -- GRANT SELECT ON INSIS_CUST.LF_EVT_DATA_CONF_INEP04 TO &1;
  GRANT SELECT ON INSIS_CUST.CUST_CORRESPONDENCE TO &1;
  GRANT UPDATE ON INSIS_CUST.CUST_CORRESPONDENCE TO &1;
  GRANT SELECT ON INSIS_CUST.POLICY_LABEL TO &1;

--------------------------------------------------------------------------------------------------------------------------------------------------------
--FA.20160531   privileges for approve underwriting  issues
  GRANT SELECT ON INSIS_CUST.UW_LIST TO &1 ;    
  GRANT execute  ON INSIS_CUST.P_CUST_UWLIST_TYPE TO &1 ; 
  GRANT execute ON INSIS_CUST.GVAR_CUST   TO &1 ;
--FA.20170313 Grant for anticimex functionality
   GRANT execute ON INSIS_CUST.SRV_CUST_POL_DM  TO &1 ;
  GRANT SELECT ON INSIS_CUST.BOAT_REGISTRY TO &1;
  GRANT INSERT ON INSIS_CUST.BOAT_REGISTRY TO &1;
  --FA.20170807 GRANTS to update INSIS BLC log level
  GRANT SELECT ON insis_gen_blc_v10.blc_values TO &1;        
  GRANT UPDATE ON insis_gen_blc_v10.blc_values TO &1;
  GRANT SELECT ON  insis_gen_blc_v10.blc_lookups  TO &1; 
   GRANT UPDATE ON  insis_gen_blc_v10.blc_lookups  TO &1; 

  --FA.20160701 EXECUTE TO UPDATE OBJECT LEVEL DEDUCT VALUE

                                    grant execute on INSIS_CUST.CUST_POL_DS  to &1;
                                    grant select on INSIS_SYS_V10.QUEST_QUESTIONS    to  &1;

                                             grant execute on INSIS_SYS_V10.SYS_DAYS    to &1; 
    GRANT UPDATE ON INSIS_GEN_V10.INSURED_OBJECT TO      &1 ; 
   --FA.20160719     Client migration
    GRANT EXECUTE ON  INSIS_CUST.PPL_TYPES TO &1;

---FA.20160704 GRANT execute for store vclients address instead of call evebt that calls integration point 
  GRANT execute ON  INSIS_CUST.CUST_POL_DM    TO &1 ;

--FA.20160602 Update renewal date
  grant execute  on INSIS_CUST.SRV_CUST_BO to &1  ;

GRANT SCHEDULER_ADMIN TO &1;
GRANT CONNECT TO &1;
GRANT RESOURCE TO &1;
-- +++ anb 2018/07/09 there is no use for this JAVAUSERPRIV
--GRANT JAVAUSERPRIV TO &1;

--GRANT INSIS_DBA TO &1;
grant execute on sys.dbms_lock to &1;
grant DATAPUMP_IMP_FULL_DATABASE to &1;

--'GRANT'||PRIVILEGE||'TO'||GRANTEE||DECODE(ADMIN_OPTION,'YES','WITHADMINOPTION','')||';'
----------------------------------------------------------------------------------------------
GRANT MANAGE SCHEDULER TO &1;
GRANT DEBUG CONNECT SESSION TO &1;
GRANT CREATE ANY DIRECTORY TO &1;
GRANT CREATE SYNONYM TO &1;
GRANT CREATE TABLE TO &1;
GRANT CREATE PROCEDURE TO &1;
GRANT CREATE PUBLIC SYNONYM TO &1;
GRANT CREATE ANY SYNONYM TO &1;
GRANT DROP ANY DIRECTORY TO &1;
GRANT DEBUG ANY PROCEDURE TO &1;
GRANT CREATE VIEW TO &1;
GRANT CREATE ANY TABLE TO &1;
GRANT CREATE JOB TO &1;
GRANT CREATE SEQUENCE TO &1;
GRANT CREATE SESSION TO &1;
GRANT CREATE EXTERNAL JOB TO &1;
GRANT CREATE ANY PROCEDURE TO &1;
GRANT UNLIMITED TABLESPACE TO &1;

--'GRANT'||PRIVILEGE||'ON'||OWNER||'.'||TABLE_NAME||'TO'||GRANTEE||DECODE(GRANTABLE,'YES','WITHGRANTOPTION','')||';'
---------------------------------------------------------------------------------------------------------------------
GRANT DEBUG ON INSIS_GEN_CFG_V10.GVAR_RB TO &1;
GRANT DEBUG ON INSIS_PEOPLE_V10.SRV_PEOPLE_DATA TO &1;
GRANT DEBUG ON INSIS_SYS_V10.INSIS_CONTEXT TO &1;
GRANT DEBUG ON INSIS_SYS_V10.PARAM TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SERVICE_MENU TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SERVICE_MENU_PROCESS TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_CONTEXT TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRVCONTEXT TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRVCONTEXTATR TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_DOCUMENT_DATA TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_DOCUMENT_DM TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_DOCUMENT_DS TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRVERR TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRVERRMSG TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_ERROR TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRVEVENT TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_EVENTS TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_EVENTS_DOCUMENT TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_EVENTS_QUESTION TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_EVENTS_SYSTEM TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_EVENTS_UTILS TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_LOG TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRVPARAM TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_PRM_DOC TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_PRM_QUEST TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_PRM_SYS TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_PRM_WFM TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_SYS_DS TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRVSYSPARAMS TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_SYSTEM TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_SYSTEM_DATA TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SRV_WFM_BO TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SYS_BASE_UTILS TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SYS_CONTEXT_UTILS TO &1 WITH GRANT OPTION;
GRANT DEBUG ON INSIS_SYS_V10.SYS_ENV TO &1 WITH GRANT OPTION;

--'GRANT'||PRIVILEGE||'ON'||OWNER||'.'||TABLE_NAME||'TO'||GRANTEE||DECODE(GRANTABLE,'YES','WITHGRANTOPTION','')||';'
-----------------------------------------------------------------------------------------------------------------------
GRANT EXECUTE ON INSIS_GEN_CFG_V10.GVAR_RB TO &1;
GRANT EXECUTE ON INSIS_PEOPLE_V10.SRV_PEOPLE_DATA TO &1;
GRANT EXECUTE ON INSIS_SYS_V10.INSIS_CONTEXT TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.PARAM TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SERVICE_MENU TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SERVICE_MENU_PROCESS TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_CONTEXT TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRVCONTEXT TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRVCONTEXTATR TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_DOCUMENT_DATA TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_DOCUMENT_DM TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_DOCUMENT_DS TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRVERR TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRVERRMSG TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_ERROR TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRVEVENT TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_EVENTS TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_EVENTS_DOCUMENT TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_EVENTS_QUESTION TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_EVENTS_SYSTEM TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_EVENTS_UTILS TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_LOG TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRVPARAM TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_PRM_DOC TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_PRM_QUEST TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_PRM_SYS TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_PRM_WFM TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_QUESTION_DATA TO &1;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_SYS_DS TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRVSYSPARAMS TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_SYSTEM TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_SYSTEM_DATA TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SRV_WFM_BO TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SYS_BASE_UTILS TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SYS_CONTEXT_UTILS TO &1 WITH GRANT OPTION;
GRANT EXECUTE ON INSIS_SYS_V10.SYS_ENV TO &1 WITH GRANT OPTION;


---- GRANT Selects
--'GRANT'||PRIVILEGE||'ON'||OWNER||'.'||TABLE_NAME||'TO'||GRANTEE||DECODE(GRANTABLE,'YES','WITHGRANTOPTION','')||';'
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GRANT SELECT ON INSIS_GEN_V10.GEN_ANNEX TO &1;
GRANT SELECT ON INSIS_GEN_V10.GEN_COVERS_SELECT TO &1;
GRANT SELECT ON INSIS_GEN_V10.GEN_RISK_TERITORY TO &1;
GRANT SELECT ON INSIS_GEN_V10.INSURED_OBJECT TO &1;
GRANT SELECT ON INSIS_GEN_V10.O_ADDEQUIPMENT TO &1;
GRANT SELECT ON INSIS_GEN_V10.O_OBJECTS TO &1;
GRANT SELECT ON INSIS_GEN_V10.O_SHIP TO &1 WITH GRANT OPTION;
GRANT SELECT ON INSIS_GEN_V10.POLICY TO &1;
GRANT SELECT ON INSIS_GEN_V10.POLICY_ADDRESSES TO &1;
GRANT UPDATE ON INSIS_GEN_V10.POLICY_ADDRESSES TO &1;
GRANT SELECT ON INSIS_GEN_V10.POLICY_AGENTS TO &1;
GRANT SELECT ON INSIS_GEN_V10.POLICY_CONDITIONS TO &1;
GRANT UPDATE ON INSIS_GEN_V10.POLICY_CONDITIONS TO &1;
GRANT SELECT ON INSIS_GEN_V10.POLICY_INFO TO &1;
GRANT SELECT ON INSIS_GEN_V10.POLICY_PARTICIPANTS_SEQ TO &1;
GRANT SELECT ON INSIS_GEN_V10.POLICY_PARTICIPANTS TO &1;
GRANT SELECT ON INSIS_GEN_V10.POLICY_PREM_FLG TO &1;
GRANT SELECT ON INSIS_GEN_V10.POLICY_ENDORSEMENTS TO &1;


-- +++ anb 2019-05-27 replace MIG_POL Discount
GRANT SELECT ON INSIS_GEN_V10.PREM_INST_INTERIM TO &1;        
GRANT UPDATE ON INSIS_GEN_V10.PREM_INST_INTERIM TO &1;  

GRANT SELECT ON  INSIS_CUST.POLICY_RENEWALS_MIG_SEQ TO &1;
GRANT INSERT ON  INSIS_CUST.POLICY_RENEWALS_MIG TO &1;

GRANT SELECT ON INSIS_PEOPLE_V10.P_ADDRESS TO &1 WITH GRANT OPTION;
GRANT SELECT ON INSIS_PEOPLE_V10.P_AGENTS TO &1 WITH GRANT OPTION;
GRANT SELECT ON INSIS_PEOPLE_V10.P_BENEFICIENTS TO &1 WITH GRANT OPTION;
GRANT SELECT ON INSIS_PEOPLE_V10.P_CLIENTS TO &1 WITH GRANT OPTION;
GRANT SELECT ON INSIS_PEOPLE_V10.P_OFFICES TO &1 WITH GRANT OPTION;
GRANT SELECT ON INSIS_PEOPLE_V10.P_PEOPLE TO &1 WITH GRANT OPTION;
GRANT SELECT ON INSIS_PEOPLE_V10.P_ROLE TO &1 WITH GRANT OPTION;


GRANT SELECT ON INSIS_GEN_CFG_V10.CPRS_OBJECT_UDFLD TO &1 WITH GRANT OPTION;
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GRANT UPDATE ON INSIS_GEN_V10.GEN_COVERS_SELECT TO &1;
GRANT UPDATE ON INSIS_GEN_V10.GEN_RISK_TERITORY TO &1;
GRANT UPDATE ON INSIS_GEN_V10.POLICY TO &1;
GRANT UPDATE on INSIS_GEN_V10.POLICY_ENDORSEMENTS to &1;
GRANT update on INSIS_GEN_V10.O_SHIP    to &1;
GRANT update on INSIS_SYS_V10.DOC_DOCUMENTS to &1;  
 GRANT update on INSIS_GEN_V10.POLICY   to &1;
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  GRANT execute on INSIS_CUST.CUST_POL_BO to &1;

  --FA.20161130 - privileges for insured object functionality
  GRANT EXECUTE ON INSIS_GEN_V10.POL_TYPES TO &1;
  GRANT EXECUTE ON INSIS_GEN_V10.P_INSOBJ_TYPE TO &1;
  GRANT EXECUTE ON INSIS_GEN_V10.P_POLICY_TYPE TO &1;
  GRANT EXECUTE ON INSIS_GEN_V10.P_COVER_TYPE TO &1;
  GRANT EXECUTE ON INSIS_GEN_V10.P_INDEMNITY_TYPE TO &1;
  GRANT EXECUTE ON INSIS_GEN_V10.GVAR_PAS TO &1;
  GRANT EXECUTE ON INSIS_GEN_V10.CURRENCY TO &1;
  GRANT EXECUTE ON INSIS_GEN_V10.P_AGENT_TYPE TO &1;
  GRANT EXECUTE ON INSIS_GEN_V10.P_AGENT_NAMES_TYPE TO &1;
  GRANT UPDATE  ON INSIS_CUST.POLICY_EXTRA_ATTR TO &1;

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  -- pl 20170110 privileges for MD Discounts
  GRANT SELECT  ON INSIS_GEN_V10.GEN_RISK_DISCOUNT TO &1;
  GRANT EXECUTE ON INSIS_GEN_V10.P_DISCOUNT_TYPE TO &1;

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  --LM 24022017 - policy_engagement_billing
  GRANT SELECT  ON INSIS_GEN_V10.POLICY_ENGAGEMENT_BILLING TO &1;
  GRANT EXECUTE ON INSIS_GEN_V10.P_ENGAGEMENT_BILLING_TYPE TO &1;

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  -- pl 20170410 acl privileges
  --exec dbms_network_acl_admin.CREATE_ACL(acl => 'mail_resolve.xml', description => 'resolve mail server', principal => &1, is_grant => true, privilege => 'resolve');
  --BEGIN dbms_network_acl_admin.ADD_PRIVILEGE(acl => 'mail_resolve.xml', principal => '''' || &1 || '''', is_grant => true, privilege => 'connect'); END;
  --BEGIN dbms_network_acl_admin.ADD_PRIVILEGE(acl => 'mail_resolve.xml', principal => '''' || &1 || '''', is_grant => true, privilege => 'resolve'); END;
  --exec dbms_network_acl_admin.assign_acl(acl => 'mail_resolve.xml', host => 'mailint.lfnet.se');
  --/*DECLARE
   -- vCount NUMBER;
  --  vUser  VARCHAR2(50) := '&1';
  --BEGIN
  --  SELECT COUNT('x') INTO vCount FROM DBA_NETWORK_ACLS dna WHERE ACL = '/sys/acls/mail_resolve.xml';
  --
  --  IF vCount = 1 THEN
  --    DBMS_OUTPUT.PUT_LINE('ACL mail_resolve.xml exists');
  --    dbms_network_acl_admin.ADD_PRIVILEGE(acl => 'mail_resolve.xml', principal => vUser, is_grant => true, privilege => 'connect');
  --    dbms_network_acl_admin.ADD_PRIVILEGE(acl => 'mail_resolve.xml', principal => vUser, is_grant => true, privilege => 'resolve');
  --  ELSE
  --    DBMS_OUTPUT.PUT_LINE('ACL mail_resolve.xml does not exists');
  --    dbms_network_acl_admin.CREATE_ACL(acl => 'mail_resolve.xml', description => 'resolve mail server', principal => vUser, is_grant => true, privilege => 'resolve');
  --    dbms_network_acl_admin.ADD_PRIVILEGE(acl => 'mail_resolve.xml', principal => vUser, is_grant => true, privilege => 'connect');
  --    dbms_network_acl_admin.assign_acl(acl => 'mail_resolve.xml', host => 'mailint.lfnet.se');
  --  END IF;

  --END;
  --*/
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--- +++ anb 2017-04-11 needed for Reconciliation views
      
GRANT select on INSIS_GEN_V10.BLC_POLICY_PAYMENT_PLAN_FRACT to &1 WITH GRANT OPTION;
GRANT select on INSIS_GEN_V10.BLC_POLICY_PAYMENT_PLAN to &1 WITH GRANT OPTION;
GRANT select on INSIS_GEN_V10.HS_GEN_COVER to &1 WITH GRANT OPTION;
GRANT select on INSIS_GEN_V10.BLC_COMMISSION_FRACT to &1 WITH GRANT OPTION;
GRANT select on INSIS_GEN_V10.BLC_COMMISSION to &1 WITH GRANT OPTION;
GRANT select on INSIS_GEN_V10.HST_OBJECT_TYPE to &1 WITH GRANT OPTION;
GRANT select on INSIS_GEN_V10.gen_risk_covered to &1 WITH GRANT OPTION;
GRANT select on INSIS_GEN_V10.HS_GEN_COVER to &1 WITH GRANT OPTION;
GRANT select on insis_gen_v10.O_PROPERTY to &1 WITH GRANT OPTION;
GRANT select on INSIS_GEN_V10.HST_POLICY_STATE to &1 WITH GRANT OPTION;
GRANT select on INSIS_GEN_V10.O_ACCINSURED to &1 WITH GRANT OPTION;

GRANT SELECT ON SYS.V_$THREAD to &1;
GRANT SELECT ON SYS.V_$parameter to &1;

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 --+++ FA. 20170613 needed for user accounts setup
  GRANT SELECT ON INSIS_PEOPLE_V10.P_STAFF TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_PEOPLE_V10.P_USER_ACCOUNTS TO &1 WITH GRANT OPTION;

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 --+++ anb 20181203 needed for EY_BI setup
  GRANT SELECT ON INSIS_GEN_V10.POLICY_ANNEX TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.GEN_ANNEX_REASON TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.HST_ANNEX_TYPE TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.HT_ANNEX_REASON TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.HST_PAYMENT_TYPE TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.HST_PAYMENT_WAY TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.HST_PAYMENT_MODE TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_CFG_V10.CFG_NL_PRODUCT TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_CFG_V10.SYSCFG_PRODUCT_LOB TO &1 WITH GRANT OPTION;
  
  GRANT SELECT ON INSIS_GEN_V10.POLICY_ENG_POLICIES TO &1 WITH GRANT OPTION;
  GRANT SELECT ON insis_gen_v10.HST_ENG_POLICY_TYPE TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.POLICY_ENGAGEMENT TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.HST_POLICY_STATE TO &1 WITH GRANT OPTION; 
  GRANT SELECT ON INSIS_GEN_V10.HST_ENGAGEMENT_TYPE TO &1 WITH GRANT OPTION;
  GRANT SELECT ON insis_gen_v10.HST_POLICY_STATE_AUX TO &1 WITH GRANT OPTION;
  
  GRANT SELECT ON insis_gen_cfg_v10.cfg_nl_covers TO &1 WITH GRANT OPTION;
  GRANT SELECT ON insis_gen_cfg_v10.CPR_COVER TO &1 WITH GRANT OPTION;
  GRANT SELECT ON insis_gen_cfg_v10.CFG_NL_PRODUCT TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_CFG_V10.SYSCFG_PRODUCT_STATUS TO &1 WITH GRANT OPTION;
  GRANT SELECT ON insis_gen_cfg_v10.SYSCFG_GL_FRACT TO &1 WITH GRANT OPTION;
  GRANT SELECT ON insis_gen_cfg_v10.SYSCFG_TARIFF_RULE TO &1 WITH GRANT OPTION;
  GRANT SELECT ON insis_gen_cfg_v10.SYSCFG_COVER_DESIGNATION TO &1 WITH GRANT OPTION;
  GRANT SELECT ON insis_gen_cfg_v10.SYSCFG_IV_RULE TO &1 WITH GRANT OPTION;
  GRANT SELECT ON insis_gen_cfg_v10.SYSCFG_PRODUCT_LOB TO &1 WITH GRANT OPTION;
  
  GRANT SELECT ON insis_gen_cfg_v10.cfg_nl_product TO &1 WITH GRANT OPTION;
  GRANT SELECT ON insis_gen_cfg_v10.cfg_nl_objects TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_CFG_V10.CPR_OBJECTS TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.insured_object TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.HST_ACTIVITY_TYPE TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.HST_IV_TYPE TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.HST_POLICY_STATE_AUX TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.HST_IV_BASE TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.HST_DUR_DIMENSION TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.HST_OBJECT_STATE TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.HST_LOCATION_RISK_CLASS TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.HST_LOCVAL_DIMENSION TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.HT_RISK_CLASS TO &1 WITH GRANT OPTION;
  GRANT SELECT ON INSIS_GEN_V10.gen_annex TO &1 WITH GRANT OPTION;

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--- +++ anb 20160426 NOT needed DO NOT USE

--GRANT SELECT ON INSIS_PEOPLE_V10.BASE_UTIL_DELETE_OBJECTS TO &1 WITH GRANT OPTION;

--GRANT SELECT ON INSIS_GEN_V10.POLICY_DECLARATION TO &1;
--GRANT SELECT ON INSIS_GEN_V10.POLICY_DECLARATION_CONDITIONS TO &1;
--GRANT SELECT ON INSIS_GEN_V10.POLICY_DECLARATION_RATES TO &1;
--GRANT SELECT ON INSIS_GEN_V10.POLICY_ENGAGEMENT_PREMIUMS TO &1;

--GRANT SELECT ON INSIS_PEOPLE_V10.GEN_AGENT_COMMISSIONS TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HST_AGENT_STATE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HST_PEOPLE_INSURER_TYPE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HST_PEOPLE_MAN_COMP TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HST_PEOPLE_SEX TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HST_SRV_STATE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HST_STAFF_ACCESS_LEVEL TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_ADDRESS_TYPE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_AGENT_LEVEL TO &1 WITH GRANT OPTION;
--
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_AGENT_TYPE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_CC_TYPE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_CONTRACT_TYPES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_CUSTOMER_ACCEPT_MARKETINFO TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_CUSTOMER_CORP_STAT TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_CUSTOMER_DATA_PERMISSION TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_CUSTOMER_EMPLOYEE_STATUS TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_CUSTOMER_INTERNAL_STATUS TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_CUSTOMER_OFFICIAL_STATUS TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_CUSTOMER_PROFILE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_CUSTOMER_PROFITABILITY TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_CUSTOMER_RISK_RATING TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_CUSTOMER_SEGMENT TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_CUSTOMER_TYPE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_EXPERT_QUALIFICATION TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_NETWORK TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_PEOPLE_CLASS_CODE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_PEOPLE_CLASS_SUBCODE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_PEOPLE_COMPANY_TYPES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_PEOPLE_CONTACT_TYPES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_PEOPLE_DATA_SOURCE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_PEOPLE_GROUPS TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_PEOPLE_GROUP_TYPES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_PEOPLE_OCCUP_CODE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_PEOPLE_OCCUP_SUBCODE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_PEOPLE_OTHERS_TYPE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_PEOPLE_OTHER_SUBTYPES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_PEOPLE_RELATION TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_PEOPLE_ROLE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_PEOPLE_SALES_CHAN_SUBTYPE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_PEOPLE_SALES_CHAN_TYPE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_STAFF_OCUPATION TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_STAFF_QUALIF_LEVEL TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.HT_STREET_TYPE TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_ACCOUNT_ACCESS_LEVEL TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_ACCOUNT_AGENTS TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_ACCOUNT_BILLING_SITES TO &1 WITH GRANT OPTION;
--
--'GRANT'||PRIVILEGE||'ON'||OWNER||'.'||TABLE_NAME||'TO'||GRANTEE||DECODE(GRANTABLE,'YES','WITHGRANTOPTION','')||';'
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--GRANT SELECT ON INSIS_PEOPLE_V10.P_ACCOUNT_INSRTYPES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_ACCOUNT_LEGAL_ENTITIES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_ACCOUNT_OFFICES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_ACCOUNT_PAYMENT_SITES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_ACCOUNT_SALES_CHANNEL TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_AGENT_CHANGES TO &1 WITH GRANT OPTION;
--
--
--GRANT SELECT ON INSIS_PEOPLE_V10.P_BANK_ACCOUNT TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_BANKS TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_CASE_NAMES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_CLIENT_AUTH TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_CLIENT_CHANGES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_CONTACT_PERSONS TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_CONTACTS TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_CREDIT_CARD TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_CREDITORS TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_DATA_SOURCE_PERMISSION TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_EXPERTS TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_INSURERS TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_OTHERS TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_PEOPLE_CHANGES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_PEOPLE_GROUPS TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_PEOPLE_ID_LIST TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_PEOPLE_RELATION TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_REGIONS TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_ROLE_AGENTS TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_ROLE_BILLING_SITES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_ROLE_INSRTYPES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_ROLE_LEGAL_ENTITIES TO &1 WITH GRANT OPTION;
--
--'GRANT'||PRIVILEGE||'ON'||OWNER||'.'||TABLE_NAME||'TO'||GRANTEE||DECODE(GRANTABLE,'YES','WITHGRANTOPTION','')||';'
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--GRANT SELECT ON INSIS_PEOPLE_V10.P_ROLE_OFFICES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_ROLE_PAYMENT_SITES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_SALES_CHANNEL TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_SALES_UNIT TO &1 WITH GRANT OPTION;

--GRANT SELECT ON INSIS_PEOPLE_V10.P_STAFF_AGENTS TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_STAFF_DBROLES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_STAFF_INSRTYPES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_STAFF_OFFICES TO &1 WITH GRANT OPTION;
--GRANT SELECT ON INSIS_PEOPLE_V10.P_STAFF_QUALIFICATIONS TO &1 WITH GRANT OPTION;

----GRANT SELECT ON INSIS_PEOPLE_V10.SQLN_EXPLAIN_PLAN TO &1 WITH GRANT OPTION;





--GRANT EXECUTE ON SYS.ARCHIVE_M02 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.CSVDIR TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.DBMS_BACKUP_RESTORE TO &1;

--'GRANT'||PRIVILEGE||'ON'||OWNER||'.'||TABLE_NAME||'TO'||GRANTEE||DECODE(GRANTABLE,'YES','WITHGRANTOPTION','')||';'
---------------------------------------------------------------------------------------------------------------------
--GRANT EXECUTE ON SYS.DDL_DIR TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.LOAD_DIR TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.LOAD_DIR_20150709 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.LOAD_DIR_20150714 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.LOAD_DIR_LOAD TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.LOAD_DIR_M01 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.LOAD_DIR_M43 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.LOAD_DIR_M50 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.MIGG_SOURCE_DIR TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M02 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M02_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M03 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M03_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M04 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M04_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M08 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M08_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M09 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M09_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M10 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M10_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M11 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M11_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M14 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M14_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M15 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M15_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M16 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M16_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M21 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M21_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M24 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M24_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M27 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M27_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M28 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M28_ARCHIVE TO &1 WITH GRANT OPTION;

--'GRANT'||PRIVILEGE||'ON'||OWNER||'.'||TABLE_NAME||'TO'||GRANTEE||DECODE(GRANTABLE,'YES','WITHGRANTOPTION','')||';'
---------------------------------------------------------------------------------------------------------------
--GRANT EXECUTE ON SYS.READ_DIR_M29 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M29_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M31 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M31_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M32 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M32_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M34 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M34_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M35 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M35_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M37 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M37_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M42 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M42_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M43 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M43_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M50 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.READ_DIR_M50_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.SYS_PLSQL_2843716F_9_1 TO &1 WITH GRANT OPTION;
--GRANT EXECUTE ON SYS.TEST_DIR TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.ARCHIVE_M02 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.CSVDIR TO &1;
--GRANT READ ON SYS.CSVDIR TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.DDL_DIR TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.DMP_DIR TO &1;
--GRANT READ ON SYS.FW_DIR TO &1;
--GRANT READ ON SYS.LOAD_DIR TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.LOAD_DIR_20150709 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.LOAD_DIR_20150714 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.LOAD_DIR_LOAD TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.LOAD_DIR_M01 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.LOAD_DIR_M43 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.LOAD_DIR_M50 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.MIGG_SOURCE_DIR TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M02 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M02_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M03 TO &1 WITH GRANT OPTION;

--'GRANT'||PRIVILEGE||'ON'||OWNER||'.'||TABLE_NAME||'TO'||GRANTEE||DECODE(GRANTABLE,'YES','WITHGRANTOPTION','')||';'
----------------------------------------------------------------------------------------------------------------------------
--GRANT READ ON SYS.READ_DIR_M03_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M04 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M04_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M08 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M08_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M09 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M09_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M10 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M10_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M11 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M11_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M14 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M14_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M15 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M15_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M16 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M16_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M21 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M21_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M24 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M24_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M27 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M27_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M28 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M28_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M29 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M29_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M31 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M31_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M32 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M32_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M34 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M34_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M35 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M35_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M37 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M37_ARCHIVE TO &1 WITH GRANT OPTION;

--'GRANT'||PRIVILEGE||'ON'||OWNER||'.'||TABLE_NAME||'TO'||GRANTEE||DECODE(GRANTABLE,'YES','WITHGRANTOPTION','')||';'
--------------------------------------------------------------------------------------------------------------------
--GRANT READ ON SYS.READ_DIR_M42 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M42_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M43 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M43_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M50 TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.READ_DIR_M50_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT READ ON SYS.SYSTEMCSV TO &1;
--GRANT READ ON SYS.TEST_DIR TO &1 WITH GRANT OPTION;

--GRANT SELECT ON SYS.XKRBMSFT TO &1;
--GRANT WRITE ON SYS.ARCHIVE_M02 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.CSVDIR TO &1;
--GRANT WRITE ON SYS.CSVDIR TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.DDL_DIR TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.DMP_DIR TO &1;
--GRANT WRITE ON SYS.FW_DIR TO &1;
--GRANT WRITE ON SYS.LOAD_DIR TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.LOAD_DIR_20150709 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.LOAD_DIR_20150714 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.LOAD_DIR_LOAD TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.LOAD_DIR_M01 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.LOAD_DIR_M43 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.LOAD_DIR_M50 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.MIGG_SOURCE_DIR TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M02 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M02_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M03 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M03_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M04 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M04_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M08 TO &1 WITH GRANT OPTION;

--'GRANT'||PRIVILEGE||'ON'||OWNER||'.'||TABLE_NAME||'TO'||GRANTEE||DECODE(GRANTABLE,'YES','WITHGRANTOPTION','')||';'
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--GRANT WRITE ON SYS.READ_DIR_M08_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M09 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M09_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M10 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M10_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M11 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M11_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M14 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M14_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M15 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M15_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M16 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M16_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M21 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M21_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M24 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M24_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M27 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M27_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M28 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M28_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M29 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M29_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M31 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M31_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M32 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M32_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M34 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M34_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M35 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M35_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M37 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M37_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M42 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M42_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M43 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M43_ARCHIVE TO &1 WITH GRANT OPTION;
--
--'GRANT'||PRIVILEGE||'ON'||OWNER||'.'||TABLE_NAME||'TO'||GRANTEE||DECODE(GRANTABLE,'YES','WITHGRANTOPTION','')||';'
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--GRANT WRITE ON SYS.READ_DIR_M50 TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.READ_DIR_M50_ARCHIVE TO &1 WITH GRANT OPTION;
--GRANT WRITE ON SYS.SYSTEMCSV TO &1;
--GRANT WRITE ON SYS.TEST_DIR TO &1 WITH GRANT OPTION;


 
