


alter session set nls_Language = 'ENGLISH';

set serveroutput on FORMAT TRUNCATED;

spool spool.txt append;

-- Update schema with DEVSYT2 relative configuration data

-- Truncate tables
--
TRUNCATE TABLE ETL_EMAIL_LIST;
TRUNCATE TABLE ETL_MIGRATION_CONDITIONS;
TRUNCATE TABLE ETL_SETUP_INFO;


-- Dumping data for table ETL_EMAIL_LIST
--

 INSERT INTO ETL_EMAIL_LIST(GROUP_ID, USERNAME, EMAIL_ADDRESS, IS_ACTIVE) VALUES
(200, 'Boyatzoglou Andreas Konsult', 'Konsult.Andreas.Boyatzoglou@lansforsakringar.se', 'Y');
 INSERT INTO ETL_EMAIL_LIST(GROUP_ID, USERNAME, EMAIL_ADDRESS, IS_ACTIVE) VALUES
(200, 'Mavrogeni Lydia Konsult', 'Konsult.Lydia.Mavrogeni@lansforsakringar.se', 'Y');
INSERT INTO ETL_EMAIL_LIST(GROUP_ID, USERNAME, EMAIL_ADDRESS, IS_ACTIVE) VALUES
(200, 'Avgerou Fani Konsult', 'Konsult.Fani.Avgerou@lansforsakringar.se', 'Y');
INSERT INTO ETL_EMAIL_LIST(GROUP_ID, USERNAME, EMAIL_ADDRESS, IS_ACTIVE) VALUES
(200, 'Åhs Göran', 'goran.ahs@lansforsakringar.se', 'Y');
INSERT INTO ETL_EMAIL_LIST(GROUP_ID, USERNAME, EMAIL_ADDRESS, IS_ACTIVE) VALUES
(200, 'Mitsiou Eleni Konsult', 'Konsult.Eleni.Mitsiou@lansforsakringar.se', 'Y');

INSERT INTO ETL_EMAIL_LIST(GROUP_ID, USERNAME, EMAIL_ADDRESS, IS_ACTIVE) VALUES
(200, NULL, 'konsult.Sanyasappadu.Kandi@lansforsakringar.se', 'Y');


-- Dumping data for table ETL_MIGRATION_CONDITIONS
--
INSERT INTO ETL_MIGRATION_CONDITIONS(ID, APPLICABLE_BOLAGS, MISSED_DATA_DEADLINE, MISSED_DISCOUNTS_DEADLINE, RENEWAL_DATE, MIGR_START_DATE, MIGR_END_DATE, DISCOUNTS_END_DATE, ITERATION_STATUS) VALUES
(1, '29,27,34,50', NULL, NULL, TO_DATE('04/01/2018 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('02/27/2018 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/31/2018 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), TO_DATE('03/31/2018 23:59:59', 'MM/DD/YYYY HH24:MI:SS'), 'Pending');


-- Dumping data for table ETL_SETUP_INFO
--
INSERT INTO ETL_SETUP_INFO(MIGG_SOURCES_DIR, MIGG_DIR, MIGG_FILE_NAME, DISCOUNTS_FILE_NAME, DISCOUNT_TYPE, MIGG_DELIMITER, FILE_EXTN, MIGG_RECON_FILE_NAME, MIGG_DIR_ARCHIVE, MIGG_JOB_TRANSACTIONAL, MIGG_DEFAULT_AGENT, TASK_NAME, PARALLEL_LEVEL, MID_PARALLEL_LEVEL, MIN_PARALLEL_LEVEL, WORK_START_TIME, WORK_END_TIME, BATCH_PARALLEL_JOBS, INTERMEDIATE_TABLE_TYPE, INSIS_DEFAULT_EVENT, ARCHIVE_MODE, MIGRATE_CLIENTS, ARCHIVE_SCHEMA, MIGRATION_METHOD, SMTP_HOST, SMTP_PORT, SMTP_SENDER, CLIENT_MIGG_DIR, CLIENT_FILE_NAME, DISCOUNTS_REPORT_VIEW, COMPLETED_REMINDER_DAYS_BEFORE, CLIENT_MIGG_DIR_ARC, MIGRATION_ENVIRONMENT, DAILY_PROG_CHECK) VALUES
(NULL, NULL, '_COMPL.txt', 'MD_DISCOUNTS.txt', 'MIG_POL', '|', 'txt', 'NP427F', NULL, 'Y', 'N', 'POL_', 20, 10, 5, '06:00:00', '18:00:00', 15, 'TEMP', 'N', N'Remove', 'N', NULL, 'EVENT', 'mailint.lfnet.se', 25, 'konsult.Andreas.Boyatzoglou@lansforsakringar.se', NULL, N'CLIENT.txt', N'V_MIGR_PREMIUMS', 1, NULL, 'INSISDB', '06:00:00');

spool off;

exit;


